# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0003_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
